# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Helmsec < Formula
  desc "CLI tool to encrypt and decrypt secret files using SOPS"
  homepage "https://github.com/philipparndt/helmsec"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/philipparndt/helmsec/releases/download/v0.2.0/helmsec_darwin_x86_64.tar.gz"
      sha256 "bc17d6826639c967ecccc724f617c46fc6f1796ad03c33cc05e7db538dbd514e"

      define_method(:install) do
        bin.install "helmsec"

        begin
          bash_output = Utils.safe_popen_read({ "SHELL" => "bash" }, "#{bin}/helmsec completion bash")
          (bash_completion/"helmsec").write bash_output
        rescue => e
          opoo "Failed to install bash completion: #{e}"
        end

        begin
          zsh_output = Utils.safe_popen_read({ "SHELL" => "zsh" }, "#{bin}/helmsec completion zsh")
          (zsh_completion/"_helmsec").write zsh_output
        rescue => e
          opoo "Failed to install zsh completion: #{e}"
        end

        begin
          fish_output = Utils.safe_popen_read({ "SHELL" => "fish" }, "#{bin}/helmsec completion fish")
          (fish_completion/"helmsec.fish").write fish_output
        rescue => e
          opoo "Failed to install fish completion: #{e}"
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/philipparndt/helmsec/releases/download/v0.2.0/helmsec_darwin_arm64.tar.gz"
      sha256 "5edd0c7f94853d0eb85dac93dfd9a0063f617892b5d81b7ad6fa818059a16c22"

      define_method(:install) do
        bin.install "helmsec"

        begin
          bash_output = Utils.safe_popen_read({ "SHELL" => "bash" }, "#{bin}/helmsec completion bash")
          (bash_completion/"helmsec").write bash_output
        rescue => e
          opoo "Failed to install bash completion: #{e}"
        end

        begin
          zsh_output = Utils.safe_popen_read({ "SHELL" => "zsh" }, "#{bin}/helmsec completion zsh")
          (zsh_completion/"_helmsec").write zsh_output
        rescue => e
          opoo "Failed to install zsh completion: #{e}"
        end

        begin
          fish_output = Utils.safe_popen_read({ "SHELL" => "fish" }, "#{bin}/helmsec completion fish")
          (fish_completion/"helmsec.fish").write fish_output
        rescue => e
          opoo "Failed to install fish completion: #{e}"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/philipparndt/helmsec/releases/download/v0.2.0/helmsec_linux_x86_64.tar.gz"
      sha256 "98541ba65cdccb30469397b3646c833b65fb31ce136c7c4b8065a5d224b0b2b9"
      define_method(:install) do
        bin.install "helmsec"

        begin
          bash_output = Utils.safe_popen_read({ "SHELL" => "bash" }, "#{bin}/helmsec completion bash")
          (bash_completion/"helmsec").write bash_output
        rescue => e
          opoo "Failed to install bash completion: #{e}"
        end

        begin
          zsh_output = Utils.safe_popen_read({ "SHELL" => "zsh" }, "#{bin}/helmsec completion zsh")
          (zsh_completion/"_helmsec").write zsh_output
        rescue => e
          opoo "Failed to install zsh completion: #{e}"
        end

        begin
          fish_output = Utils.safe_popen_read({ "SHELL" => "fish" }, "#{bin}/helmsec completion fish")
          (fish_completion/"helmsec.fish").write fish_output
        rescue => e
          opoo "Failed to install fish completion: #{e}"
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/philipparndt/helmsec/releases/download/v0.2.0/helmsec_linux_arm64.tar.gz"
      sha256 "1d45d8d38cabd95fdbdc375e3213ee4dc8eaf5fd5ee238e184ed9a62b32070f1"
      define_method(:install) do
        bin.install "helmsec"

        begin
          bash_output = Utils.safe_popen_read({ "SHELL" => "bash" }, "#{bin}/helmsec completion bash")
          (bash_completion/"helmsec").write bash_output
        rescue => e
          opoo "Failed to install bash completion: #{e}"
        end

        begin
          zsh_output = Utils.safe_popen_read({ "SHELL" => "zsh" }, "#{bin}/helmsec completion zsh")
          (zsh_completion/"_helmsec").write zsh_output
        rescue => e
          opoo "Failed to install zsh completion: #{e}"
        end

        begin
          fish_output = Utils.safe_popen_read({ "SHELL" => "fish" }, "#{bin}/helmsec completion fish")
          (fish_completion/"helmsec.fish").write fish_output
        rescue => e
          opoo "Failed to install fish completion: #{e}"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Run using helmsec.
    EOS
  end
end
