# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Helmsec < Formula
  desc "CLI tool to encrypt and decrypt secret files using SOPS"
  homepage "https://github.com/philipparndt/helmsec"
  version "0.3.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/philipparndt/helmsec/releases/download/v0.3.1/helmsec_darwin_x86_64.tar.gz"
      sha256 "8d48e5d44e0e89dea7f2f30f5da94083dad1f4fe8b687354f5e8f96da46a6730"

      define_method(:install) do
        bin.install "helmsec"

        begin
          bash_output = Utils.safe_popen_read({ "SHELL" => "bash" }, "#{bin}/helmsec completion bash")
          (bash_completion/"helmsec").write bash_output
        rescue => e
          opoo "Failed to install bash completion: #{e}"
        end

        begin
          zsh_output = Utils.safe_popen_read({ "SHELL" => "zsh" }, "#{bin}/helmsec completion zsh")
          (zsh_completion/"_helmsec").write zsh_output
        rescue => e
          opoo "Failed to install zsh completion: #{e}"
        end

        begin
          fish_output = Utils.safe_popen_read({ "SHELL" => "fish" }, "#{bin}/helmsec completion fish")
          (fish_completion/"helmsec.fish").write fish_output
        rescue => e
          opoo "Failed to install fish completion: #{e}"
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/philipparndt/helmsec/releases/download/v0.3.1/helmsec_darwin_arm64.tar.gz"
      sha256 "bd50d99e6af9904a8bdcd506395bdc099ebf6a49f5d26fb2d2c8ac7eca09b7a8"

      define_method(:install) do
        bin.install "helmsec"

        begin
          bash_output = Utils.safe_popen_read({ "SHELL" => "bash" }, "#{bin}/helmsec completion bash")
          (bash_completion/"helmsec").write bash_output
        rescue => e
          opoo "Failed to install bash completion: #{e}"
        end

        begin
          zsh_output = Utils.safe_popen_read({ "SHELL" => "zsh" }, "#{bin}/helmsec completion zsh")
          (zsh_completion/"_helmsec").write zsh_output
        rescue => e
          opoo "Failed to install zsh completion: #{e}"
        end

        begin
          fish_output = Utils.safe_popen_read({ "SHELL" => "fish" }, "#{bin}/helmsec completion fish")
          (fish_completion/"helmsec.fish").write fish_output
        rescue => e
          opoo "Failed to install fish completion: #{e}"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/philipparndt/helmsec/releases/download/v0.3.1/helmsec_linux_x86_64.tar.gz"
      sha256 "ed42b5619ffacc2914c9fefc720e9d9df020cc4c0979d299c7bf4881c6023893"
      define_method(:install) do
        bin.install "helmsec"

        begin
          bash_output = Utils.safe_popen_read({ "SHELL" => "bash" }, "#{bin}/helmsec completion bash")
          (bash_completion/"helmsec").write bash_output
        rescue => e
          opoo "Failed to install bash completion: #{e}"
        end

        begin
          zsh_output = Utils.safe_popen_read({ "SHELL" => "zsh" }, "#{bin}/helmsec completion zsh")
          (zsh_completion/"_helmsec").write zsh_output
        rescue => e
          opoo "Failed to install zsh completion: #{e}"
        end

        begin
          fish_output = Utils.safe_popen_read({ "SHELL" => "fish" }, "#{bin}/helmsec completion fish")
          (fish_completion/"helmsec.fish").write fish_output
        rescue => e
          opoo "Failed to install fish completion: #{e}"
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/philipparndt/helmsec/releases/download/v0.3.1/helmsec_linux_arm64.tar.gz"
      sha256 "43c7f3425e65d93d9e2fa96b27d14fddfb8f4601577404cf8015c7600b1e772c"
      define_method(:install) do
        bin.install "helmsec"

        begin
          bash_output = Utils.safe_popen_read({ "SHELL" => "bash" }, "#{bin}/helmsec completion bash")
          (bash_completion/"helmsec").write bash_output
        rescue => e
          opoo "Failed to install bash completion: #{e}"
        end

        begin
          zsh_output = Utils.safe_popen_read({ "SHELL" => "zsh" }, "#{bin}/helmsec completion zsh")
          (zsh_completion/"_helmsec").write zsh_output
        rescue => e
          opoo "Failed to install zsh completion: #{e}"
        end

        begin
          fish_output = Utils.safe_popen_read({ "SHELL" => "fish" }, "#{bin}/helmsec completion fish")
          (fish_completion/"helmsec.fish").write fish_output
        rescue => e
          opoo "Failed to install fish completion: #{e}"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Run using helmsec.
    EOS
  end
end
