# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Helmsec < Formula
  desc "CLI tool to encrypt and decrypt secret files using SOPS"
  homepage "https://github.com/philipparndt/helmsec"
  version "0.3.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/philipparndt/helmsec/releases/download/v0.3.2/helmsec_darwin_x86_64.tar.gz"
      sha256 "c0d0a091246b7a992c7865ca7659de39f40e1d63f5e0e6cb5af13a15634cebca"

      define_method(:install) do
        bin.install "helmsec"

        begin
          bash_output = Utils.safe_popen_read({ "SHELL" => "bash" }, "#{bin}/helmsec completion bash")
          (bash_completion/"helmsec").write bash_output
        rescue => e
          opoo "Failed to install bash completion: #{e}"
        end

        begin
          zsh_output = Utils.safe_popen_read({ "SHELL" => "zsh" }, "#{bin}/helmsec completion zsh")
          (zsh_completion/"_helmsec").write zsh_output
        rescue => e
          opoo "Failed to install zsh completion: #{e}"
        end

        begin
          fish_output = Utils.safe_popen_read({ "SHELL" => "fish" }, "#{bin}/helmsec completion fish")
          (fish_completion/"helmsec.fish").write fish_output
        rescue => e
          opoo "Failed to install fish completion: #{e}"
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/philipparndt/helmsec/releases/download/v0.3.2/helmsec_darwin_arm64.tar.gz"
      sha256 "13077ee3fafa6dea395922c8b65cac8944cacf2d4812f1ed1c015784ff7f094c"

      define_method(:install) do
        bin.install "helmsec"

        begin
          bash_output = Utils.safe_popen_read({ "SHELL" => "bash" }, "#{bin}/helmsec completion bash")
          (bash_completion/"helmsec").write bash_output
        rescue => e
          opoo "Failed to install bash completion: #{e}"
        end

        begin
          zsh_output = Utils.safe_popen_read({ "SHELL" => "zsh" }, "#{bin}/helmsec completion zsh")
          (zsh_completion/"_helmsec").write zsh_output
        rescue => e
          opoo "Failed to install zsh completion: #{e}"
        end

        begin
          fish_output = Utils.safe_popen_read({ "SHELL" => "fish" }, "#{bin}/helmsec completion fish")
          (fish_completion/"helmsec.fish").write fish_output
        rescue => e
          opoo "Failed to install fish completion: #{e}"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/philipparndt/helmsec/releases/download/v0.3.2/helmsec_linux_x86_64.tar.gz"
      sha256 "06669bb529b549e2891432579f5d6295da6e33c7046a2397f155a78f0e104e84"
      define_method(:install) do
        bin.install "helmsec"

        begin
          bash_output = Utils.safe_popen_read({ "SHELL" => "bash" }, "#{bin}/helmsec completion bash")
          (bash_completion/"helmsec").write bash_output
        rescue => e
          opoo "Failed to install bash completion: #{e}"
        end

        begin
          zsh_output = Utils.safe_popen_read({ "SHELL" => "zsh" }, "#{bin}/helmsec completion zsh")
          (zsh_completion/"_helmsec").write zsh_output
        rescue => e
          opoo "Failed to install zsh completion: #{e}"
        end

        begin
          fish_output = Utils.safe_popen_read({ "SHELL" => "fish" }, "#{bin}/helmsec completion fish")
          (fish_completion/"helmsec.fish").write fish_output
        rescue => e
          opoo "Failed to install fish completion: #{e}"
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/philipparndt/helmsec/releases/download/v0.3.2/helmsec_linux_arm64.tar.gz"
      sha256 "01f094d94d1e566f85ff8234f1b12c783568002819ff9b680175f7d4bba9e55c"
      define_method(:install) do
        bin.install "helmsec"

        begin
          bash_output = Utils.safe_popen_read({ "SHELL" => "bash" }, "#{bin}/helmsec completion bash")
          (bash_completion/"helmsec").write bash_output
        rescue => e
          opoo "Failed to install bash completion: #{e}"
        end

        begin
          zsh_output = Utils.safe_popen_read({ "SHELL" => "zsh" }, "#{bin}/helmsec completion zsh")
          (zsh_completion/"_helmsec").write zsh_output
        rescue => e
          opoo "Failed to install zsh completion: #{e}"
        end

        begin
          fish_output = Utils.safe_popen_read({ "SHELL" => "fish" }, "#{bin}/helmsec completion fish")
          (fish_completion/"helmsec.fish").write fish_output
        rescue => e
          opoo "Failed to install fish completion: #{e}"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Run using helmsec.
    EOS
  end
end
